---
site_name: "test-github-actions.github.io"
site_author: "Tobias Wohland"
site_description: "Static test documentation"

repo_url: "https://github.com/TobiWo/test-github-actions"

theme:
  name: "material"
  palette:
    scheme: "slate"
    primary: "blue grey"
  features:
    - "navigation.instant"
    - "navigation.tracking"
    - "navigation.sections"
    - "navigation.prune"
    - "navigation.top"
    - "content.code.copy"

markdown_extensions:
  # Python Markdown
  - "abbr"
  - "admonition"
  - "attr_list"
  - "def_list"
  - "footnotes"
  - "md_in_html"
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: "all"
  - "pymdownx.caret"
  - "pymdownx.details"
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: "__span"
      pygments_lang_class: true
  - "pymdownx.inlinehilite"
  - "pymdownx.snippets"
  - "pymdownx.superfences"
  - "pymdownx.keys"
  - "pymdownx.mark"
  - "pymdownx.smartsymbols"
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - "pymdownx.tilde"

extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/TobiWo/test-github-actions"
    - icon: "fontawesome/brands/x-twitter"
      link: "https://twitter.com/TobiWoWo"

extra_css:
  - stylesheets/extra.css

nav:
  - Home: "./index.md"
  - Part 1:
    - Introduction: "part1/introduction.md"
    - General Information: "part1/general.md"
  - Part 2:
    - Introduction: "part2/introduction.md"
...
