FROM python:3.12.0-alpine3.18

RUN python3 -m pip install \
  pyyaml==6.0.1 \
  requests==2.31.0

RUN adduser -D app
USER app

WORKDIR /home/app

COPY duties ./duties

ENTRYPOINT [ "python", "duties/main.py" ]
