---
name: "Main"

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  mkdocs-deploy-job:
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4.1.7"
      - name: "Set up python and pip cache"
        uses: "actions/setup-python@v5.2.0"
        with:
          python-version: "3.12.5"
          cache: "pip"
      - name: "Install dependencies"
        run: "pip install -r requirements.txt"
      - name: "Generate mkdocs cache id"
        run: "echo \"cache_id=$(date --utc '+%V')\" >> $GITHUB_ENV"
      - name: "Set up mkdocs cache"
        uses: "actions/cache@v4.0.2"
        with:
          path: "~/.cache/"
          key: "mkdocs-material-${{ env.cache_id }}"
          restore-keys: |
            mkdocs-material-
      - name: "Deploy documentation"
        run: "mkdocs gh-deploy --force"
...
